version: '3'
services:
  pdq-api:
    image: oxime/pdq:api
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
  pdq-van-module:
    image: oxime/pdq:vans
    stdin_open: true
    tty: true
    depends_on:
      - pdq-api
